# Generated by Django 4.1.5 on 2023-01-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'categoriaProd', 'verbose_name_plural': 'categoriasProductos'},
        ),
    ]
